.TH WMBUSMETERS 1
.SH NAME
wmbusmeters-admin \- Interactively configure devices and meters for wireless mbus and wired mbus.

.SH SYNOPSIS
.B wmbusmeters-admin {options}

.SH DESCRIPTION

Wmbusmeters-admin is used to configure and test wmbus devices.

.SH OPTIONS
\fB\--debug\fR for a lot of information

\fB\--verbose\fR for more information

\fB\--version\fR print version

.SH AUTHOR
Written by Fredrik Öhrström.

.SH COPYRIGHT
Copyright \(co 2017-2022 Fredrik Öhrström.
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
