#!/bin/sh

set -e

# Add the wmbusmeters group unless it's already there
addgroup --quiet --system wmbusmeters || true

# creating wmbusmeters user unless it's already there
if ! getent passwd wmbusmeters >/dev/null; then
        adduser --system --ingroup wmbusmeters \
                --home / --no-create-home \
                --gecos "wmbusmeters daemon" \
                wmbusmeters
fi

#DEBHELPER#
