name: Lint
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint_xmq:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: |
         sudo apt install -y eatmydata
         sudo eatmydata apt-get install librtlsdr-dev libusb-dev libxml2-dev libxslt1-dev
    - id: BUILD_XMQ
      run: eatmydata ./configure && make build/xmq && chmod +x ./build/xmq && cp ./build/xmq /usr/local/bin/xmq
    - id: LINT_XMQ
      run: eatmydata make pretty
      working-directory: drivers
    - id: GIT_DIFF
      run: |
        if ! git diff --quiet drivers; then
        echo "Code is not properly formatted. Please run 'make pretty'in /drivers and commit the changes."
        exit 1
        fi

  integrity_authors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: GENERATE_AUTHORS
      run: ./scripts/generate_authors.sh ./src/authors.h
    - id: GIT_DIFF
      run: |
        if ! git diff --quiet src; then
        echo "authors.h is not up to date. Please run './scripts/generate_authors.sh ./src/authors.h' and commit the changes."
        exit 1
        fi


  integrity_short_manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: GENERATE_SHORT_MANUAL
      run: ./scripts/generate_short_manual.sh ./src/short_manual.h
    - id: GIT_DIFF
      run: |
        if ! git diff --quiet src; then
        echo "short_manual.h is not up to date. Please run './scripts/generate_short_manual.sh ./src/short_manual.h' and commit the changes."
        exit 1
        fi
